// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// dotenv/config's default behavior only loads .env, never .env.local -- but
// this project's real secrets (pulled in by `vercel integration add neon`)
// live in .env.local, per Next.js's own convention. Loading .env.local
// explicitly here is what makes the CLI actually see the real DATABASE_URL
// instead of silently falling back to .env's placeholder scaffold value.
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local" });
loadEnv(); // .env as a fallback for anything .env.local doesn't set

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need Neon's DIRECT (non-pooled) connection -- Prisma's
    // migration engine uses session-level features (advisory locks, etc.)
    // that don't work reliably through Neon's pooled/pgbouncer-style
    // endpoint. The app itself (lib/db.ts) is unaffected by this file and
    // correctly keeps using the pooled DATABASE_URL at runtime, which is
    // the right choice for serverless. See .claude/skills/neon-postgres.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
